import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ActivityIndicator } from 'react-native';
import YoutubePlayer from 'react-native-youtube-iframe';
import api from '../services/api';

const VideoPlayerScreen = ({ route }) => {
    const { title, streamUrl } = route.params;
    const [videoData, setVideoData] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchStreamInfo();
    }, []);

    const fetchStreamInfo = async () => {
        try {
            const response = await api.get(streamUrl);
            setVideoData(response.data);
        } catch (error) {
            console.error('Stream info error', error);
        } finally {
            setLoading(false);
        }
    };

    return (
        <View style={styles.container}>
            <Text style={styles.title}>{title}</Text>

            {loading ? (
                <ActivityIndicator size="large" color="#ff0050" />
            ) : (
                <View style={styles.videoContainer}>
                    {videoData?.youtube_id ? (
                        <YoutubePlayer
                            height={250}
                            play={false}
                            videoId={videoData.youtube_id}
                        />
                    ) : (
                        <Text style={{ color: '#fff' }}>Video not found</Text>
                    )}
                </View>
            )}

            <View style={styles.details}>
                <Text style={styles.status}>Masked Stream: Active</Text>
                <Text style={styles.statusText}>This URL is dynamically generated by the backend to keep the source private.</Text>
            </View>
        </View>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
        paddingTop: 50,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
        padding: 20,
        textAlign: 'center',
    },
    videoContainer: {
        width: '100%',
        height: 250,
        backgroundColor: '#111',
    },
    video: {
        flex: 1,
    },
    details: {
        padding: 20,
    },
    status: {
        color: '#ff0050',
        fontWeight: 'bold',
        fontSize: 14,
        marginBottom: 5,
    },
    statusText: {
        color: '#888',
        fontSize: 12,
    },
});

export default VideoPlayerScreen;
